version: '3'
services:
    client-ms:
      image: webdevops/php-nginx:8.0-alpine
      volumes:
        - ./client-ms:/app
      ports:
        - '8080:80'
      environment:
        - WEB_DOCUMENT_ROOT=/app/public
      networks:
        - ms-network

networks:
  ms-network:
    driver: bridge
