version: '3'
services:
    kong:
      image: kong
      environment:
        - KONG_DATABASE=off
        - KONG_PROXY_ACCESS_LOG=/dev/stdout
        - KONG_DECLARATIVE_CONFIG=/usr/local/kong/declarative/kong.yml
        - KONG_ADMIN_ACCESS_LOG=/dev/stdout
        - KONG_PROXY_ERROR_LOG=/dev/stderr
        - KONG_ADMIN_ERROR_LOG=/dev/stderr
        - KONG_ADMIN_LISTEN=0.0.0.0:8001
        - KONG_ADMIN_GUI_URL=http://localhost:8002
      ports:
        - "8000:8000"
        - "8001:8001"
        - "8002:8002"
      volumes:
        - ./docker/kong/kong.yml:/usr/local/kong/declarative/kong.yml
      networks:
        - ms-network
    client-ms:
      image: webdevops/php-nginx:8.0-alpine
      working_dir: /app
      deploy:
        replicas: 1
      ports:
        - "8080:80"
      volumes:
        - ./client-ms:/app
      environment:
        - WEB_DOCUMENT_ROOT=/app/public
      networks:
        - ms-network
    client-worker:
      image: webdevops/php-nginx:8.0-alpine
      command: sh -c "sleep 5; php /app/artisan rabbitmq:consume"
      depends_on:
        - rabbitmq
      volumes:
        - ./client-ms:/app
      networks:
        - ms-network
    client-db:
      image: postgres:13-alpine
      volumes:
        - client-postgres-data:/var/lib/postgresql/data
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_DB=client
        - POSTGRES_USER=client
        - POSTGRES_PASSWORD=client
      networks:
        - ms-network
    rabbitmq:
      image: rabbitmq:3-management-alpine
      environment:
        - RABBITMQ_DEFAULT_VHOST=poc
        - RABBITMQ_DEFAULT_USER=user
        - RABBITMQ_DEFAULT_PASS=password
      ports:
        - "8081:15672"
      networks:
        - ms-network

volumes:
  client-postgres-data:
    driver: local

networks:
  ms-network:
    driver: bridge
