version: '3'
services:
  kong:
    image: kong
    environment:
      - KONG_DATABASE=off
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_DECLARATIVE_CONFIG=/usr/local/kong/declarative/kong.yml
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_ADMIN_GUI_URL=http://localhost:8002
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    volumes:
      - ./docker/kong/kong.yml:/usr/local/kong/declarative/kong.yml
    networks:
      - ms-network
  client-ms:
    image: webdevops/php-nginx:8.0-alpine
    working_dir: /app
    deploy:
      replicas: 2
    volumes:
      - ./client-ms:/app
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
    networks:
      - ms-network
  client-db:
    image: postgres:13-alpine
    volumes:
      - client-postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=client
      - POSTGRES_USER=client
      - POSTGRES_PASSWORD=client
    networks:
      - ms-network
  registration-information-ms:
    image: webdevops/php-nginx:8.0-alpine
    working_dir: /app
    deploy:
      replicas: 2
    volumes:
      - ./registration-information-ms:/app
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
    networks:
      - ms-network
  registration-information-db:
    image: postgres:13-alpine
    volumes:
      - registration-information-postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=registration-information
      - POSTGRES_USER=registration-information
      - POSTGRES_PASSWORD=registration-information
    networks:
      - ms-network
  data-science-bi:
    image: webdevops/php-nginx:8.0-alpine
    depends_on:
      - rabbitmq
    volumes:
      - ./data-science-bi-ms:/app
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
    networks:
      - ms-network
  data-science-bi-worker:
    image: webdevops/php-nginx:8.0-alpine
    command: sh -c "sleep 5; php /app/artisan rabbitmq:consume"
    depends_on:
      - rabbitmq
    volumes:
      - ./data-science-bi-ms:/app
    networks:
      - ms-network
  strategic-management:
    image: webdevops/php-nginx:8.0-alpine
    working_dir: /app
    depends_on:
      - rabbitmq
    volumes:
      - ./strategic-management-ms:/app
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
    networks:
      - ms-network
  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      - RABBITMQ_DEFAULT_VHOST=poc
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "8081:15672"
    networks:
      - ms-network
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
    networks:
      - ms-network

volumes:
  client-postgres-data:
    driver: local
  registration-information-postgres-data:
    driver: local

networks:
  ms-network:
    driver: bridge
