_format_version: "2.1"
_transform: true

services:
  - name: client
    url: http://client-ms/
    #  plugins:
    #  - name: key-auth
    routes:
      - name: client
        paths:
          - /client
  - name: data-science-bi
    url: http://data-science-bi/
    routes:
      - name: data-science-bi
        paths:
          - /data-science-bi
  - name: strategic-management
    url: http://strategic-management/
    routes:
      - name: strategic-management
        paths:
          - /strategic-management
  - name: registration-information
    url: http://registration-information-ms/
    routes:
      - name: registration-information
        paths:
          - /registration-information

plugins:
  - name: cors
    service: client
    config:
      origins:
        - http://localhost:3000
      methods:
        - GET
        - POST
      headers:
        - Accept
        - Accept-Version
        - Content-Length
        - Content-MD5
        - Content-Type
        - Date
        - X-Auth-Token
      exposed_headers:
        - X-Auth-Token
      credentials: true
      max_age: 3600
      preflight_continue: false
  - name: cors
    service: registration-information
    config:
      origins:
        - http://localhost:3000
      methods:
        - GET
        - POST
      headers:
        - "*"
      exposed_headers:
        - X-Auth-Token
      credentials: true
      max_age: 3600
      preflight_continue: false
consumers:
  - username: my-user
#  keyauth_credentials:
#  - key: my-key
