_format_version: "2.1"
_transform: true

services:
  - name: client
    url: http://client-ms/
  #  plugins:
  #  - name: key-auth
    routes:
    - name: client
      paths:
      - /client
  - name: data-science-bi
    url: http://data-science-bi/
    routes:
    - name: data-science-bi
      paths:
      - /data-science-bi
consumers:
- username: my-user
#  keyauth_credentials:
#  - key: my-key
