_format_version: "2.1"
_transform: true

services:
  - name: client
    url: http://client-ms/
    #  plugins:
    #  - name: key-auth
    routes:
      - name: client
        paths:
          - /client
  - name: data-science-bi
    url: http://data-science-bi/
    routes:
      - name: data-science-bi
        paths:
          - /data-science-bi
  - name: strategic-management
    url: http://strategic-management/
    routes:
      - name: strategic-management
        paths:
          - /strategic-management
  - name: registration-information
    url: http://registration-information-ms/
    routes:
      - name: registration-information
        paths:
          - /registration-information
consumers:
  - username: my-user
#  keyauth_credentials:
#  - key: my-key
